;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Skill.Input.A",DevComment="")
+GameplayTagList=(Tag="Skill.Input.E",DevComment="")
+GameplayTagList=(Tag="Skill.Input.None",DevComment="")
+GameplayTagList=(Tag="Skill.Input.Q",DevComment="")
+GameplayTagList=(Tag="Skill.Input.R",DevComment="")
+GameplayTagList=(Tag="State.Block",DevComment="")
+GameplayTagList=(Tag="State.Buff.Gaurd",DevComment="")
+GameplayTagList=(Tag="State.Buff.Heist",DevComment="")
+GameplayTagList=(Tag="State.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="State.Buff.Tenacity",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Fear",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Knockback",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Root",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Silence",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Slow",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Taunt",DevComment="")
+GameplayTagList=(Tag="State.Enemy.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Enemy.Dead",DevComment="")
+GameplayTagList=(Tag="State.Enemy.Following",DevComment="")
+GameplayTagList=(Tag="State.Enemy.Idle",DevComment="")
+GameplayTagList=(Tag="State.Exorcist.Casting",DevComment="")
+GameplayTagList=(Tag="State.Exorcist.Dead",DevComment="")
+GameplayTagList=(Tag="State.Exorcist.Idle",DevComment="")
+GameplayTagList=(Tag="State.Exorcist.Moving",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Burn",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Dark",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Electric",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Freeze",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Light",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Plague",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Rock",DevComment="")
+GameplayTagList=(Tag="State.SkillType.Wind",DevComment="")
+GameplayTagList=(Tag="State.Stack.Burn",DevComment="")
+GameplayTagList=(Tag="State.Stack.Dark",DevComment="")
+GameplayTagList=(Tag="State.Stack.Electric",DevComment="")
+GameplayTagList=(Tag="State.Stack.Freeze",DevComment="")
+GameplayTagList=(Tag="State.Stack.Light",DevComment="")
+GameplayTagList=(Tag="State.Stack.Plague",DevComment="")
+GameplayTagList=(Tag="State.Stack.Rock",DevComment="")
+GameplayTagList=(Tag="State.Stack.Wind",DevComment="")

