// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/GameInstance.h"
#include "GameplayTagContainer.h"
#include "GameplayTagsClasses.h"
#include "EAEGameInstance.generated.h"

class UGameplayTagsManager;

namespace Tags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Exorcist_Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Exorcist_Moving);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Exorcist_Casting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Exorcist_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Following);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Attacking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Dead);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Gaurd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Heist);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Shield);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_Tenacity);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Fear);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Knockback);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Root);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Silence);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Slow);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Stun);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Taunt);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Burn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Dark);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Electric);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Freeze);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Plauge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Rock);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillType_Wind);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Burn);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Dark);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Electric);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Freeze);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Light);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Plauge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Rock);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack_Wind);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_None);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_A);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Q);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_E);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_R);
}

/**
 * 
 */
UCLASS()
class EXORCISEANDENVOY_API UEAEGameInstance : public UGameInstance
{
	GENERATED_BODY()
	
public:
	UEAEGameInstance();

		
};
